# Generated by Django 5.0.6 on 2026-09-27 13:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('held_on', models.DateField()),
                ('sign_in_opens', models.DateTimeField()),
                ('sign_in_closes', models.DateTimeField()),
                ('sign_out_opens', models.DateTimeField()),
                ('sign_out_closes', models.DateTimeField()),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.activity')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.department')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.level')),
            ],
            options={
                'ordering': ['-held_on'],
                'unique_together': {('department', 'level', 'activity', 'held_on')},
            },
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('direction', models.CharField(choices=[('in', 'Sign in'), ('out', 'Sign out')], max_length=3)),
                ('source', models.CharField(choices=[('scan', 'Scanned'), ('manual', 'Manual entry')], default='scan', max_length=6)),
                ('manual_reason', models.CharField(blank=True, max_length=255)),
                ('scanned_at', models.DateTimeField(help_text='Device clock — when the student was actually at the door')),
                ('received_at', models.DateTimeField(auto_now_add=True, help_text='Server clock — when this record arrived')),
                ('device_id', models.CharField(max_length=100)),
                ('capture_path', models.ImageField(blank=True, null=True, upload_to='captures/')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='students.student')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='attendance.session')),
            ],
            options={
                'ordering': ['scanned_at'],
            },
        ),
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('burst', 'Burst — many scans in a few seconds on one device'), ('missing_out', 'Signed in, never signed out'), ('orphan_out', 'Signed out with no sign-in'), ('short_dwell', 'Out minus in under threshold'), ('out_of_window', 'Outside the declared window'), ('clock_skew', 'Device clock looks wrong'), ('manual_heavy', 'High share of manual entries this session')], max_length=20)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('raised_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution', models.TextField(blank=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_flags', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flags', to='students.student')),
                ('scan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flags', to='attendance.scan')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='attendance.session')),
            ],
            options={
                'ordering': ['-raised_at'],
            },
        ),
        migrations.AddIndex(
            model_name='scan',
            index=models.Index(fields=['session', 'scanned_at'], name='scan_session_time_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='scan',
            unique_together={('session', 'student', 'direction')},
        ),
    ]
