# Generated by Django 5.0.6 on 2026-09-27 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_no', models.CharField(max_length=40, unique=True)),
                ('first_name', models.CharField(max_length=80)),
                ('surname', models.CharField(max_length=80)),
                ('other_names', models.CharField(blank=True, max_length=80)),
                ('email', models.EmailField(blank=True, help_text='Used for the one-time self-service login code', max_length=254)),
                ('photo', models.ImageField(blank=True, help_text='Captured at self-registration — this is the enrolment photo shown at every scan', null=True, upload_to='student_photos/')),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('roster_matched', models.BooleanField(default=False, help_text='True if reg_no matched RosterReference at registration')),
                ('rejection_reason', models.CharField(blank=True, max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='core.department')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='core.level')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_students', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['reg_no'],
            },
        ),
        migrations.CreateModel(
            name='LoginCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_codes', to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='RosterReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_no', models.CharField(max_length=40)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_roster_entries', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roster_entries', to='core.department')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roster_entries', to='core.level')),
            ],
            options={
                'ordering': ['reg_no'],
                'unique_together': {('department', 'level', 'reg_no')},
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_sha256', models.CharField(max_length=64, unique=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='students.student')),
            ],
            options={
                'indexes': [models.Index(fields=['token_sha256'], name='card_token_idx')],
            },
        ),
    ]
